/**
 * All possible actions enum.
 */
const actions = {
    NOT_FOUND_POPUP: "NOT FOUND POPUP",
    BAD_DATA_POPUP: "BAD DATA POPUP",
    RELOAD: "RELOAD",
    LEAVE_QUEUE: "LEAVE QUEUE",
    LOGOUT: "LOGOUT",
    SOMETHING_WENT_WRONG_POPUP: "SOMETHING WENT WRONG POPUP",
    GO_TO_DECKS_PAGE: "GO TO DECKS PAGE",
    LOGIN: "LOGIN",
    CARDS_NOT_FOUND_POPUP: "CARDS NOT FOUND POPUP",
    CARD_NOT_FOUND_POPUP: "CARD NOT FOUND POPUP",
    NATION_NOT_FOUND_POPUP: "NATION NOT FOUND POPUP",
    NOT_AN_OWNER_POPUP: "NOT AN OWNER POPUP",
    DECK_NOT_FOUND: "DECK NOT FOUND",
    NATIONS_NOT_FOUND_POPUP: "NATIONS NOT FOUND POPUP",
    REDIRECT_TO_PACKS_PAGE: "REDIRECT TO PACKS PAGE",
    PACK_NOT_FOUND_POPUP: "PACK NOT FOUND POPUP",
    CHANGE_DECK_LIST_ACCORDINGLY: "CHANGE DECK LIST ACCORDINGLY",
    REDIRECT_TO_MAIN_SCREEN: "REDIRECT TO MAIN SCREEN",
    FOCUS_ON_SIZE: "FOCUS ON SIZE",
    ACCOUNT_NOT_CONFIRMED_POPUP: "ACCOUNT NOT CONFIRMED POPUP",
    RELOAD_PAGE: "RELOAD PAGE",
    JOIN_QUEUE: "JOIN QUEUE",
    DISPLAY_CHANGE_YOUR_DECK_POPUP: "DISPLAY CHANGE YOUR DECK POPUP",
    CHANGE_DECKS_LIST: "CHANGE DECKS LIST",
    INSUFFICIENT_FUNDS_POPUP: "INSUFFICIENT FUNDS POPUP",
    REFUND: "REFUND",
    GO_TO_CARDS: "GO TO CARDS",
    TRY_LATER_POPUP: "TRY LATER POPUP",
    FOCUS_ON_SIZE_FIELD: "FOCUS ON SIZE FIELD"
}

module.exports = {
    actions
}