/**
 * All possible statuses enum.
 */
const statuses = {
    NOT_FOUND: "NOT FOUND",
    BAD_DATA: "BAD DATA",
    NATION_NOT_FOUND: "NATION NOT FOUND",
    OK: "OK",
    SOMETHING_WENT_WRONG: "SOMETHING WENT WRONG",
    USER_NOT_FOUND: "USER NOT FOUND",
    NOT_SYNCHRONIZED: 'NOT SYNCHRONIZED',
    DECK_NOT_FOUND: "DECK NOT FOUND",
    DECK_NATIONS_ARE_DIFFERENT: "DECK NATIONS ARE DIFFERENT"
}

module.exports = { statuses }