/**
 * All possible actions enum.
 */
const actions = {
    NOT_FOUND_POPUP: "NOT_FOUND_POPUP",
    LOGOUT: "LOGOUT",
    LOGIN: "LOGIN",
    ADMIN: "ADMIN",
    BAD_DATA: "BAD DATA",
    BAD_DATA_POPUP: "BAD DATA POPUP",
    BAD_SECRET_KEY: "BAD SECRET KEY",
    USER_NOT_FOUND: "USER NOT FOUND",
    USER_NOT_FOUND_POPUP: "USER NOT FOUND POPUP",
    USER_IS_BANNED: "USER IS BANNED",
    USERS_FOUND: "USERS FOUND",
    ACCOUNT_CONFIRMED_POPUP: "ACCOUNT CONFIRMED POPUP",
    SOMETHING_WENT_WRONG_POPUP: "SOMETHING WENT WRONG POPUP",
    BAD_TOKEN_POPUP: "BAD TOKEN POPUP",
    ACCOUNT_ALREADY_CONFIRMED_POPUP: "ACCOUNT ALREADY CONFIRMED POPUP",
    BAD_REQUEST_POPUP: "BAD REQUEST POPUP",
    GO_TO_USERS: "GO TO USERS",
    DISPLAY_USER_INFO_AND_EDIT_FORM: "DISPLAY USER INFO AND EDIT FORM",
    DISPLAY_USER_INFO_AND_BANHAMMER: "DISPLAY USER INFO AND BANHAMMER",
    DISPLAY_USER_INFO: "DISPLAY USER INFO",
    SHOW_USERS: "SHOW USERS",
    USERS_FOUND_AND_SHOW_BANHAMMER: "USERS FOUND AND SHOW BANHAMMER",
    DISPLAY_LINK_TO_RESOURCE: "DISPLAY LINK TO RESOURCE",
    NOTHING: "NOTHING",
    USER_BAN_SUCCESS_POPUP: "USER BAN SUCCESS POPUP",
    PASSWORDS_DO_NOT_MATCH_POPUP: "PASSWORDS DO NOT MATCH POPUP",
    USER_EXISTS_POPUP: "USER EXISTS POPUP",
    REGISTERED_POPUP: "REGISTERED POPUP",
    NO_ACCESS_TOKEN_POPUP: "NO ACCESS TOKEN POPUP",
    BAD_OPERATION_POPUP: "BAD OPERATION POPUP",
    BOUGHT_POPUP: "BOUGHT POPUP",
    INSUFFICIENT_FUNDS_POPUP: "INSUFFICIENT FUNDS POPUP",
    ACCOUNT_ADMINED_POPUP: "ACCOUNT ADMINED POPUP",
    EMAIL_ALREADY_TAKEN_POPUP: "EMAIL ALREADY TAKEN POPUP",
    EMAIL_CHANGED_POPUP: "EMAIL CHANGED POPUP",
    PASSWORD_CHANGED_POPUP: "PASSWORD CHANGED POPUP",
    USERNAME_CHANGED_POPUP: "USERNAME CHANGED POPUP",
    BAD_PASSWORD_POPUP: "BAD PASSWORD POPUP",
    REFUNDED_POPUP: "REFUNDED_POPUP"
}

module.exports = {
    actions
}