/**
 * All possible statuses enum.
 */
const statuses = {
    NOT_FOUND: "NOT_FOUND",
    BAD_DATA: "BAD_DATA",
    USER_NOT_FOUND: "USER NOT FOUND",
    USER_FOUND: "USER FOUND",
    USER_IS_BANNED: "USER IS BANNED",
    USER_NOT_AUTHORIZED: "USER NOT AUTHORIZED",
    USER_LOGGED_IN: "USER LOGGED IN",
    ADMIN: "ADMIN",
    BAD_SECRET_KEY: "BAD SECRET KEY",
    USERS_FOUND: "USERS FOUND",
    ACCOUNT_CONFIRMED: "ACCOUNT CONFIRMED",
    ACCOUNT_NOT_CONFIRMED: "ACCOUNT NOT CONFIRMED",
    BAD_TOKEN: "BAD TOKEN",
    ACCOUNT_ALREADY_CONFIRMED: "ACCOUNT ALREADY CONFIRMED",
    SOMETHING_WENT_WRONG: "SOMETHING WENT WRONG",
    USER_NOT_BANNED: "USER NOT BANNED",
    USER_BANNED: "USER BANNED",
    PASSWORDS_DO_NOT_MATCH: "PASSWORDS DO NOT MATCH",
    OK: "OK",
    NO_ACCESS_TOKEN: "NO ACCESS TOKEN",
    PASSWORD_EMAIL_SENT: "PASSWORD EMAIL SENT",
    YOU_CANNOT_START_YOUR_OWN_BUY_CALL: "YOU CANNOT START YOUR OWN BUY CALL",
    BOUGHT: "BOUGHT",
    INSUFFICIENT_FUNDS: "INSUFFICIENT FUNDS",
    USER_IS_ADMIN: "USER IS ADMIN",
    YOU_ARE_NOT_AN_ADMIN: "YOU ARE NOT AN ADMIN",
    EMAIL_ALREADY_REGISTERED: "EMAIL ALREADY REGISTERED"
}

module.exports = { statuses }